class AbstractSignatureScheme:
    """
    This is the definition of the interface of a signature scheme.
    """
    @staticmethod
    def keygen():
        """returns a (public, private)-keypair."""
        raise NotImplementedError

    @staticmethod
    def sign(privkey, message):
        """returns a signature. The privkey is the private key
        generated by keygen. The message is an array of bytes.
        """
        raise NotImplementedError

    @staticmethod
    def verify(pubkey, message, signature):
        """returns True iff the signature is correct."""
        raise NotImplementedError
